#!/bin/bash
# add port 'deviceName', 'linkName', 'lat', 'lng', 'ship'(optional for mobile cpe) next to the .py command to spawn new processes 

#python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5001 device01 SanJose 33 -120 &
#python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5002 device02 MountainView 32 -115 &

# bash file in - /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/static/bash/sim
python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5001 Device01 Catalina_LongBeach 33.722523 -118.216988 ship &
python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5002 Device02 Catalina_SanBernadino 33.722523 -118.216988 ship &
python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5003 Device03 Cleveland_SanBernadino 33.796110 -117.652387 &
python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5004 Device04 SantaAna_Irvine 33.732124 -117.900595 &
python /Users/saswata_basu/code/gigaknot/nms/deviceSimulator/deviceSimulator.py 5005 Device05 Pacific_Huntington 33.637279 -118.003592 ship &
